---
title: "rds"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(flextable)
library(officer)
```


```{r}
Data <- readRDS("Applications/test_tox.rds")
```

```{r}

```



```{r create plotData}

plotData <- data.frame(matrix(ncol = 13 ))
column_names <- c("Study", "Species", "Months", "Dose", "NOAEL", "Cmax", "AUC", "Findings", "Reversibility", "Severity", "Value", "NOAEL_all", "value_order")
colnames(plotData) <- column_names


count <- 1

for (Study in names(Data[["Nonclinical Information"]])) {
  if (Study != "New Study") {
    studyData <- Data[["Nonclinical Information"]][[Study]]
    
    for (i in seq(studyData$nFindings)){
      for (j in seq(studyData$nDoses)){
        
        plotData[count, "Study"] <- Study
        plotData[count, "Species"] <- studyData[["Species"]]
        plotData[count, "Months"] <- studyData[["Duration"]]
        plotData[count, "Dose"] <- studyData[["Doses"]][[paste0("Dose", j)]][["Dose"]]
        plotData[count, "NOAEL"] <- studyData[["Doses"]][[paste0("Dose",j)]][["NOAEL"]]
        plotData[count, "Cmax"] <- studyData[["Doses"]][[paste0("Dose", j)]][["Cmax"]]
        plotData[count, "AUC"] <- studyData[["Doses"]][[paste0("Dose", j)]][["AUC"]]
        plotData[count, "Findings"] <- studyData[["Findings"]][[paste0("Finding", i)]][["Finding"]]
        plotData[count, "Reversibility"] <- studyData[["Findings"]][[paste0("Finding", i)]][["Reversibility"]]
        plotData[count, "Severity"] <- studyData[["Findings"]][[paste0("Finding", i)]][["Severity"]][[paste0("Dose", j)]]
        plotData[count, "Value"] <- 1
        plotData[count, "value_order"] <- j
        plotData[count, "NOAEL_all"] <- paste0("Dose:", studyData[["Doses"]][[paste0("Dose", j)]][["Dose"]], ",",
                                               " AUC:", studyData[["Doses"]][[paste0("Dose", j)]][["AUC"]], ",",
                                               " Cmax: ", studyData[["Doses"]][[paste0("Dose", j)]][["Cmax"]])
        count <- count+1
        
      }
    }
  }
}

plotData$Rev <- gsub("\\[|\\]", "", plotData$Reversibility)
plotData$finding_rev <- paste0(plotData$Findings,"_", plotData$Rev)
plotData$find_rev_b <- paste0(plotData$Findings, plotData$Reversibility)

head(plotData)

```



```{r key findings}
plotData <- data.frame(matrix(ncol = 8 ))
column_names <- c("Study", "Species", "Months", "Dose", "NOAEL",  "Findings",  "Severity",  "Key_findings")
colnames(plotData) <- column_names
#plotData$NOAEL_all <- as.character(plotData$NOAEL_all)

count <- 1

for (Study in names(Data[["Nonclinical Information"]])) {
  if (Study != "New Study") {
    studyData <- Data[["Nonclinical Information"]][[Study]]
    for (i in seq(studyData$nFindings)){
      for (j in seq(studyData$nDoses)){
        
        plotData[count, "Study"] <- Study
        plotData[count, "Species"] <- studyData[["Species"]]
        plotData[count, "Months"] <- studyData[["Duration"]]
        plotData[count, "Dose"] <- studyData[["Doses"]][[paste0("Dose", j)]][["Dose"]]
        plotData[count, "NOAEL"] <- studyData[["Doses"]][[paste0("Dose",j)]][["NOAEL"]]
        plotData[count, "Cmax"] <- studyData[["Doses"]][[paste0("Dose", j)]][["Cmax"]]
        plotData[count, "AUC"] <- studyData[["Doses"]][[paste0("Dose", j)]][["AUC"]]
        plotData[count, "Findings"] <- studyData[["Findings"]][[paste0("Finding", i)]][["Finding"]]
        plotData[count, "Reversibility"] <- studyData[["Findings"]][[paste0("Finding", i)]][["Reversibility"]]
        plotData[count,"Severity"] <- studyData[["Findings"]][[paste0("Finding", i)]][["Severity"]][[paste0("Dose", j)]]
        plotData[count, "Value"] <- 1
        
        plotData[count, "NOAEL_all"] <- paste0("Dose:", studyData[["Doses"]][[paste0("Dose", j)]][["Dose"]], ",",
                                               " AUC:", studyData[["Doses"]][[paste0("Dose", j)]][["AUC"]], ",",
                                               " Cmax: ", studyData[["Doses"]][[paste0("Dose", j)]][["Cmax"]])
        
       
        
        count <- count+1
        
      }
    }
  }
}

plotData$Rev <- gsub("\\[|\\]", "", plotData$Reversibility)
plotData$finding_rev <- paste0(plotData$Findings,"_", plotData$Rev)
plotData$find_rev_b <- paste0(plotData$Findings, plotData$Reversibility)

plotData

```



```{r}
tab_02 <- plotData %>% 
  select(Study,NOAEL,Dose,NOAEL_all, Findings) %>% 
  filter(NOAEL == TRUE) %>% 
  group_by(Study, Dose) %>% 
  select(-(NOAEL))
print(tab_02)
```

```{r flextable}
tab_02_flex <- flextable(tab_02) %>% 
  theme_box()
```

```{r}
tab_merge <- merge_v(tab_02_flex, j = ~ Study + Dose +NOAEL_all)
tab_merge
```

```{r}
flextable::save_as_docx(tab_merge, path= "table_03.docx")
```

```{r}
tab_merge_fin <- tab_merge %>% 
  merge_v
```

```{r}

```



```{r editing, eval=FALSE, include=FALSE}

    # rd_plot <- data.frame(Study = NA, Species = NA, Months = NA, Dose = NA,
    #                   NOAEL = NA, Findings = NA, Severity = NA, Value = 1)

plotData <- data.frame(Study=NA,Dose=NA,Cmax=NA,AUC=NA,NOAEL=NA,doseFindings=NA, Severity = NA)

count <- 1
for (Study in names(Data[['Nonclinical Information']])) {
  if (Study != 'New Study') {
    studyData <- Data[['Nonclinical Information']][[Study]]
    Doses <- NULL
    Cmaxs <- NULL
    AUCs <- NULL
    NOAELs <- NULL
    Severitys <- NULL
    
    for (i in seq(studyData$nDoses)) {
      Doses[i] <- studyData$Doses[[paste0('Dose',i)]][['Dose']]
      Cmaxs[i] <- studyData$Doses[[paste0('Dose',i)]][['Cmax']]
      AUCs[i] <- studyData$Doses[[paste0('Dose',i)]][['AUC']]
      NOAELs[i] <- studyData$Doses[[paste0('Dose',i)]][['NOAEL']]
      Severitys[i] <- studyData$Findings[[paste0("Finding", i)]][["Severity"]][[paste0("Dose", i)]]
    }
    
    
    # 
    # Findings <- NULL
    # Reversible <- NULL
    # FindingDoses <- NULL
    # Severities <- NULL
    # if (studyData$nFindings>0) {
    #   for (i in seq(studyData$nFindings)) {
    #     Findings[i] <- studyData$Findings[[paste0('Finding',i)]][['Finding']]
    #     Reversible[i] <- studyData$Findings[[paste0('Finding',i)]][['Reversibility']]
    #     FindingDoses[i] <- paste(studyData$Findings[[paste0('Finding',i)]][['FindingDoses']],collapse='|')
    #   }
    # }
    
    Findings <- NULL
    Reversible <- NULL
    Severities <- NULL
    
    if (studyData$nFindings > 0) {
      for (i in seq(studyData$nFindings)) {
        Findings[i] <- studyData$Findings[[paste0("Finding", i)]][["Finding"]]
        Reversible[i] <- studyData$Findings[[paste0("Finding",i)]][["Reversibility"]]
        Severities[i] <- studyData$Findings[[paste0("Finding", i)]][["Severity"]][[paste0("Dose",i)]]
      }
    }
    
    
    
    for (Dose in Doses) {
      index <- which(Doses==Dose)
      Cmax <- Cmaxs[index]
      AUC <- AUCs[index]
      NOAEL <- NOAELs[index]
      findingFlag <- F
      doseFindings <- ''
      for (Finding in Findings) {
        findingIndex <- which(Findings==Finding)
        doseFindingDoses <- unlist(strsplit(FindingDoses[findingIndex],'|',fixed = T))
        if (Dose %in% doseFindingDoses) {
          if (doseFindings == '') {
            doseFindings <- paste0(Finding,' ',Reversible[findingIndex])
          } else {
            doseFindings <- paste0(doseFindings,'\n',Finding,' ',Reversible[findingIndex])
          }
        }
      }
      plotData[count,] <- c(Study,Dose,Cmax,AUC,NOAEL,doseFindings)
      count <- count + 1
      findingFlag <- T
    }
  }
}
plotData

```

```{r eval=FALSE, include=FALSE}
getPlotData <- reactive({
    Data <- getData()
    plotData <- data.frame(Study=NA,Dose=NA,Cmax=NA,AUC=NA,NOAEL=NA,doseFindings=NA)
    count <- 1
    for (Study in names(Data[['Nonclinical Information']])) {
      if (Study != 'New Study') {
        studyData <- Data[['Nonclinical Information']][[Study]]
        Doses <- NULL
        Cmaxs <- NULL
        AUCs <- NULL
        NOAELs <- NULL
        for (i in seq(studyData$nDoses)) {
          Doses[i] <- studyData$Doses[[paste0('Dose',i)]][['Dose']]
          Cmaxs[i] <- studyData$Doses[[paste0('Dose',i)]][['Cmax']]
          AUCs[i] <- studyData$Doses[[paste0('Dose',i)]][['AUC']]
          NOAELs[i] <- studyData$Doses[[paste0('Dose',i)]][['NOAEL']]
        }
        Findings <- NULL
        Reversible <- NULL
        FindingDoses <- NULL
        if (studyData$nFindings>0) {
          for (i in seq(studyData$nFindings)) {
            Findings[i] <- studyData$Findings[[paste0('Finding',i)]][['Finding']]
            Reversible[i] <- studyData$Findings[[paste0('Finding',i)]][['Reversibility']]
            FindingDoses[i] <- paste(studyData$Findings[[paste0('Finding',i)]][['FindingDoses']],collapse='|')
          }
        }
        for (Dose in Doses) {
          index <- which(Doses==Dose)
          Cmax <- Cmaxs[index]
          AUC <- AUCs[index]
          NOAEL <- NOAELs[index]
          findingFlag <- F
          doseFindings <- ''
          for (Finding in Findings) {
            findingIndex <- which(Findings==Finding)
            doseFindingDoses <- unlist(strsplit(FindingDoses[findingIndex],'|',fixed = T))
            if (Dose %in% doseFindingDoses) {
              if (doseFindings == '') {
                doseFindings <- paste0(Finding,' ',Reversible[findingIndex])
              } else {
                doseFindings <- paste0(doseFindings,'\n',Finding,' ',Reversible[findingIndex])
              }
            }
          }
          plotData[count,] <- c(Study,Dose,Cmax,AUC,NOAEL,doseFindings)
          count <- count + 1
          findingFlag <- T
        }
      }
    }
    plotData <- plotData[which(plotData$Study %in% input$displayStudies),]
    return(plotData)
})
```


```{r}
## When passing a single vector, paste0 and paste work like as.character.
paste0(1:12)
paste(1:12)        # same
as.character(1:12) # same

## If you pass several vectors to paste0, they are concatenated in a
## vectorized way.
(nth <- paste0(1:12, c("st", "nd", "rd", rep("th", 9))))

## paste works the same, but separates each input with a space.
## Notice that the recycling rules make every input as long as the longest input.
paste(month.abb, "is the", nth, "month of the year.")
paste(month.abb, letters)

## You can change the separator by passing a sep argument
## which can be multiple characters.
paste(month.abb, "is the", nth, "month of the year.", sep = "_*_")

## To collapse the output into a single string, pass a collapse argument.
paste0(nth, collapse = ", ")

## For inputs of length 1, use the sep argument rather than collapse
paste("1st", "2nd", "3rd", collapse = ", ") # probably not what you wanted
paste("1st", "2nd", "3rd", sep = ", ")


## You can combine the sep and collapse arguments together.
paste(month.abb, nth, sep = ": ", collapse = "; ")

## Using paste() in combination with strwrap() can be useful
## for dealing with long strings.
title <- paste(strwrap(
    "Stopping distance of cars (ft) vs. speed (mph) from Ezekiel (1930)",
    width = 30), collapse = "\n")
plot(dist ~ speed, cars, main = title)
```

```{r}
plot(1, main=paste("X:",1," ","Y:", 2," ","\nZ:",3))
```


```{r}
datatable(head(iris, 20), options = list(
  initComplete = JS("
                        function(settings, json) {
                          $(this.api().table().header()).css({
                          'font-size': '12px',
                          });
                        }
                    ")
)) %>%
  formatStyle(columns = colnames(.$x$data), `font-size` = "12px")
```

